apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: weather-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weather-release-weather-chart
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
